spring:
  application:
    name: payment
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:3306/payment?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true